import Head from 'next/head'
import Image from 'next/image'
import Background from '../components/Background'
import GetInTouch from '../components/GetInTouch'
import Header from '../components/Header'
import MyStory from '../components/MyStory'
import Skills from '../components/Skills'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Background />
        <Header />
        <MyStory />
        <Skills />
        <GetInTouch />
        <Footer />
      </main>

    </div>
  )
}
